default: &default
  adapter: postgresql
  encoding: unicode
  database: iedb
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: myuser
  password: mypass
  host: blooming-coast-01603.herokuapp.com

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: iedb
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: myuser
  password: mypass
  host: blooming-coast-01603.herokuapp.com
